### ISSUE TITLE
Filter UI 

### ISSUE THREAD

**Issue by ujjwall-R** [ujjwall-R/Dree#11]
Remove unnecessary printings in terminal interface

**Comment by Saaaaaad3** [comment]
> Remove unnecessary printings in terminal interface

@ujjwall-R can you elaborate or provide screenshots for the same ?

**Comment by ujjwall-R** [comment]
Can you try installing and run the project in your machine and watch wall unnecessary details are there?

**Comment by ujjwall-R** [comment]
![image](https://github.com/ujjwall-R/Dree/assets/75781631/57268ef3-1fd1-4c33-a737-1a87ce3ee418)

**Comment by ujjwall-R** [comment]
The first 2 lines and the last line can be removed.

**Comment by Saaaaaad3** [comment]
@ujjwall-R Thank you for elaboration. Will start with it today.

**Comment by ujjwall-R** [comment]
@Saaaaaad3 Are you still working on it?
Actually I figured it out how to do so. Just add silent flag in make command in dree.sh.
