### ISSUE TITLE
Write installation script

### ISSUE THREAD

**Issue by ujjwall-R** [ujjwall-R/Dree#19]
- Linux
- MacOS

**Comment by 0xA-Waleed** [comment]
can you explain what do you mean by "installation script" ?

**Comment by ujjwall-R** [comment]
> can you explain what do you mean by "installation script" ?

We want a script which can be run and this would help skip all the setups. So basically automating the setup using script(maybe bash).

**Comment by Arpit01Goel** [comment]
I would like to do this part

**Comment by peachjelly13** [comment]
Is this like simply running a script to install dree?

**Comment by ujjwall-R** [comment]
> Is this like simply running a script to install dree?
Yes

**Comment by peachjelly13** [comment]
@ujjwall-R I would like to work on this too using both bash and python.

**Comment by peachjelly13** [comment]
@ujjwall-R Have created a pull request for the installation process , please reach out in case there is any issue.
